### ISSUE TITLE
List Js + Other Js files

### ISSUE THREAD

**Issue by zextis** [zextis/fms-ui#18]
# Re: #9 - List Js Implementation

## Tasks

- [x] Get local List.js file

- [x] Organize List Js functionality into modules

- [x] Import them to main file

- [x] Link HTML/PHP files

### 1. list.min.js

Contains a local copy of Listjs

### 2. main.js

Contains tab functionality and reset code for list.js

### 3. [modulename]_list.js

Contains list update function for respective module.
_example: request_list.js_
